# Sanitizer configuration module
# Supports: AddressSanitizer, UndefinedBehaviorSanitizer, ThreadSanitizer, LeakSanitizer, MemorySanitizer

# Options for enabling sanitizers
option(ENABLE_SANITIZER_ADDRESS "Enable AddressSanitizer" OFF)
option(ENABLE_SANITIZER_UNDEFINED "Enable UndefinedBehaviorSanitizer" OFF)
option(ENABLE_SANITIZER_LEAK "Enable LeakSanitizer" OFF)
option(ENABLE_SANITIZER_THREAD "Enable ThreadSanitizer" OFF)
option(ENABLE_SANITIZER_MEMORY "Enable MemorySanitizer (Clang only)" OFF)

# Global sanitizer setup (applies to all targets)
if(ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_UNDEFINED OR ENABLE_SANITIZER_LEAK OR 
   ENABLE_SANITIZER_THREAD OR ENABLE_SANITIZER_MEMORY)
    message(STATUS "=== Sanitizers Configuration ===")
    message(STATUS "AddressSanitizer: ${ENABLE_SANITIZER_ADDRESS}")
    message(STATUS "UndefinedBehaviorSanitizer: ${ENABLE_SANITIZER_UNDEFINED}")
    message(STATUS "LeakSanitizer: ${ENABLE_SANITIZER_LEAK}")
    message(STATUS "ThreadSanitizer: ${ENABLE_SANITIZER_THREAD}")
    message(STATUS "MemorySanitizer: ${ENABLE_SANITIZER_MEMORY}")
    message(STATUS "================================")

    if(ENABLE_SANITIZER_THREAD AND (ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_LEAK OR ENABLE_SANITIZER_MEMORY))
        message(FATAL_ERROR "ThreadSanitizer cannot be combined with AddressSanitizer, LeakSanitizer, or MemorySanitizer")
    endif()

    if(ENABLE_SANITIZER_MEMORY AND (ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_LEAK OR ENABLE_SANITIZER_THREAD))
        message(FATAL_ERROR "MemorySanitizer cannot be combined with other sanitizers")
    endif()

    set(SANITIZER_COMPILE_FLAGS "")
    set(SANITIZER_LINK_FLAGS "")

    if(ENABLE_SANITIZER_ADDRESS)
        if(MSVC)
            list(APPEND SANITIZER_COMPILE_FLAGS /fsanitize=address)
            list(APPEND SANITIZER_LINK_FLAGS /fsanitize=address)
        else()
            list(APPEND SANITIZER_COMPILE_FLAGS -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls)
            list(APPEND SANITIZER_LINK_FLAGS -fsanitize=address)
        endif()
    endif()

    if(ENABLE_SANITIZER_UNDEFINED)
        if(MSVC)
            message(WARNING "UndefinedBehaviorSanitizer is not supported by MSVC")
        else()
            list(APPEND SANITIZER_COMPILE_FLAGS -fsanitize=undefined -fno-omit-frame-pointer)
            list(APPEND SANITIZER_LINK_FLAGS -fsanitize=undefined)
            if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
                list(APPEND SANITIZER_COMPILE_FLAGS -fsanitize=integer -fsanitize=nullability)
                list(APPEND SANITIZER_LINK_FLAGS -fsanitize=integer -fsanitize=nullability)
            endif()
        endif()
    endif()

    if(ENABLE_SANITIZER_LEAK)
        if(MSVC)
            message(WARNING "LeakSanitizer is not supported by MSVC")
        else()
            list(APPEND SANITIZER_COMPILE_FLAGS -fsanitize=leak -fno-omit-frame-pointer)
            list(APPEND SANITIZER_LINK_FLAGS -fsanitize=leak)
        endif()
    endif()

    if(ENABLE_SANITIZER_THREAD)
        if(MSVC)
            message(WARNING "ThreadSanitizer is not supported by MSVC")
        else()
            list(APPEND SANITIZER_COMPILE_FLAGS -fsanitize=thread -fno-omit-frame-pointer)
            list(APPEND SANITIZER_LINK_FLAGS -fsanitize=thread)
        endif()
    endif()

    if(ENABLE_SANITIZER_MEMORY)
        if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            message(FATAL_ERROR "MemorySanitizer is only supported by Clang")
        endif()
        if(MSVC)
            message(WARNING "MemorySanitizer is not supported by MSVC")
        else()
            list(APPEND SANITIZER_COMPILE_FLAGS -fsanitize=memory -fno-omit-frame-pointer -fsanitize-memory-track-origins)
            list(APPEND SANITIZER_LINK_FLAGS -fsanitize=memory)
        endif()
    endif()

    if(SANITIZER_COMPILE_FLAGS)
        add_compile_options(${SANITIZER_COMPILE_FLAGS})
        add_link_options(${SANITIZER_LINK_FLAGS})
    endif()

    if(CMAKE_BUILD_TYPE STREQUAL "Debug" AND NOT MSVC)
        add_compile_options(-O1 -g)
    endif()
endif()
